name: ariel_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.02

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
  intl: ^0.17.0
  image_picker: ^0.8.4
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^20.1.59
  firebase_auth: ^3.3.20
  firebase_storage: ^10.0.2
  date_time_picker: ^2.1.0
  bloc_pattern: ^3.0.1
  fluttericon: ^2.0.0
  flutter_calendar_week: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
    - family: ArielIcons
      fonts:
        - asset: assets/fonts/ArielIcons.ttf