/// Flutter icons ArielIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArielIcons
///      fonts:
///       - asset: fonts/ArielIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ArielIcons {
  ArielIcons._();

  static const _kFontFam = 'ArielIcons';
  static const String? _kFontPkg = null;

  static const IconData aplicacao =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
